name: Run npm run dev

on:
  push:
    branches:
      - master

jobs:
  run-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Updated to the latest version
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20" # Ensure the latest Node.js version is used
      - name: Install dependencies
        run: npm install
      - name: Run npm run dev
        run: npm run dev
