name: Run npm run dev

on:
  push:
    branches:
      - main

jobs:
  run-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run npm run dev
        run: npm run dev
